In [69]:
import os 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns

# import seaborn as sns
def preprocess(train):
    
    #train = train[train['segment'] == 2]
    #t1

    train.head()

    ## Training only for segment 1

    #train = train[train['segment'] == 2]

    t = train[:100]
    train['day'] = train.apply(lambda x : pd.to_datetime(x['application_date']).weekday() , axis = 1)
    train['sz'] = train['state'].astype(str) + train['zone'].astype(str)
    train = train.drop(['state' , 'zone'] ,axis = 1)

    ## Mean encodings

    def mean_encodings(df , cols) :
        for col in cols :
            df['{}_enc'.format(col)] = df.groupby(col)['case_count'].transform('mean')
            #df['{}_enc'.format(col)].fillna(0.4453, inplace=True)
        return df

    cols = [ 'sz' , 'branch_id' , 'day' , 'segment']
    #cols = [ 'sz', 'day']

    train = mean_encodings(train , cols)

    train.head()

    train = pd.get_dummies(train, columns=['sz','branch_id' ,'day' , 'segment'])
    train.head()

    train.head()

    #train = train.reset_index()
    train = train.set_index(['application_date'])
    # train = train.drop(['day' , 'sz'] , axis = 1)
    train.head()
    return train
    ## Training Seg 2 :

In [70]:
def trainsp(train):

    df = train[train.index < '2019-04-01']

    val = train[train.index >= '2019-04-01']

    X_train = df.drop(['case_count'] , axis = 1)
    y_train = df['case_count'].astype(int)

    X_val = val.drop(['case_count'] , axis = 1)
    y_val = val['case_count'].astype(int)

    
    
    categorical = ['sz' , 'branch_id' , 'day' , 'segment']

    def column_index(df, query_cols):
        cols = df.columns.values
        sidx = np.argsort(cols)
        return sidx[np.searchsorted(cols, query_cols, sorter=sidx)]
    categorical_features_indices = column_index(X_train, categorical)

    X_train.head()

    #!pip install catboost
    train.info()
    
    return X_train,  y_train, X_val , y_val

In [71]:
train = train.drop(['Unnamed: 0'] , axis= 1)

KeyError: "['Unnamed: 0'] not found in axis"

In [ ]:
# train = train.drop(['branch_id'] , axis= 1)
# train.to_csv('./grpd.csv')

In [ ]:
os.listdir('./')

train = pd.read_csv('./grpd.csv',index_col = 'application_date')

train.head()

In [ ]:
y_train = train['case_count']
X_train = train.drop(['case_count'] , axis = 1)

In [73]:
test = pd.read_csv('./test_1eLl9Yf.csv')# ,  index_col = 'application_date')
test.head()
#test = test.drop(['Unnamed: 0'] , axis = 1)

   id application_date  segment
0   1       2019-07-06        1
1   2       2019-07-07        1
2   3       2019-07-08        1
3   4       2019-07-09        1
4   5       2019-07-10        1

In [74]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 3 columns):
id                  180 non-null int64
application_date    180 non-null object
segment             180 non-null int64
dtypes: int64(2), object(1)
memory usage: 4.3+ KB

In [75]:
test = test.drop(['id'] , axis =1 )
test['day'] =test.apply(lambda x : pd.to_datetime(x['application_date']).weekday() , axis = 1)
test

    application_date  segment  day
0         2019-07-06        1    5
1         2019-07-07        1    6
2         2019-07-08        1    0
3         2019-07-09        1    1
4         2019-07-10        1    2
5         2019-07-11        1    3
6         2019-07-12        1    4
7         2019-07-13        1    5
8         2019-07-14        1    6
9         2019-07-15        1    0
10        2019-07-16        1    1
11        2019-07-17        1    2
12        2019-07-18        1    3
13        2019-07-19        1    4
14        2019-07-20        1    5
15        2019-07-21        1    6
16        2019-07-22        1    0
17        2019-07-23        1    1
18        2019-07-24        1    2
19        2019-07-25        1    3
20        2019-07-26        1    4
21        2019-07-27        1    5
22        2019-07-28        1    6
23        2019-07-29        1    0
24        2019-07-30        1    1
25        2019-07-31        1    2
26        2019-08-01        1    3
27        2019-08-02        1    4
28        2019-08-03        1    5
29        2019-08-04        1    6
..               ...      ...  ...
150       2019-09-25        2    2
151       2019-09-26        2    3
152       2019-09-27        2    4
153       2019-09-28        2    5
154       2019-09-29        2    6
155       2019-09-30        2    0
156       2019-10-01        2    1
157       2019-10-02        2    2
158       2019-10-03        2    3
159       2019-10-04        2    4
160       2019-10-05        2    5
161       2019-10-06        2    6
162       2019-10-07        2    0
163       2019-10-08        2    1
164       2019-10-09        2    2
165       2019-10-10        2    3
166       2019-10-11        2    4
167       2019-10-12        2    5
168       2019-10-13        2    6
169       2019-10-14        2    0
170       2019-10-15        2    1
171       2019-10-16        2    2
172       2019-10-17        2    3
173       2019-10-18        2    4
174       2019-10-19        2    5
175       2019-10-20        2    6
176       2019-10-21        2    0
177       2019-10-22        2    1
178       2019-10-23        2    2
179       2019-10-24        2    3

[180 rows x 3 columns]

In [76]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 3 columns):
application_date    180 non-null object
segment             180 non-null int64
day                 180 non-null int64
dtypes: int64(2), object(1)
memory usage: 4.3+ KB

In [77]:
test.to_csv('test.csv')

# EXTRAAAA

In [10]:
train = pd.read_csv('./train_fwYjLYX.csv')
train = train.drop(['branch_id' , 'state' , 'zone'] ,axis = 1)
train['day'] = train.apply(lambda x : pd.to_datetime(x['application_date']).weekday() , axis = 1)

In [13]:
train.head()
train.set_index(['application_date'])
train.to_csv('./train.csv')